### ISSUE TITLE
warning when generate dynamic menu

### ISSUE THREAD

**Issue by dmaglio** [trizen/obmenu-generator#10]
```Invalid option or value: keep_empty_categories at /usr/local/share/perl5/Linux/DesktopFiles.pm line 100.```

**Comment by trizen** [comment]
The option `keep_empty_categories` can be safely removed from `config.pl` as it is a no-op anyway in the latest versions of `Linux::DesktopFiles`.

**Comment by dmaglio** [comment]
:+1:
