### ISSUE TITLE
Support Desktop ids

### ISSUE THREAD

**Issue by marcthe12** [trizen/obmenu-generator#11]
As the desktop spec specifies desktop ids, we should use them. Basically if I have a desktop file in $XDG_DATA_HOME/application called foo.desktop, it overide /usr/share/desktop. This will help when minor changes desktop files are neede and you do not want to override the desktop files in /usr/share. This useful in environmental variables or wraper functions

**Comment by trizen** [comment]
Thanks for reporting this issue!

Support for desktop IDs has been added inside the [Linux::DesktopFiles](https://metacpan.org/release/TRIZEN/Linux-DesktopFiles-0.20) module, which fixes this issue.

See also: https://github.com/trizen/Linux-DesktopFiles/commit/0d6232237e21c344d421366cf366d77c1654e6b9
