### ISSUE TITLE
Switching icons in menu

### ISSUE THREAD

**Issue by erikdubois** [trizen/obmenu-generator#14]
Hi
ArchLabs is using your obmenu-generator. It works fine for menu's without icons. But users select an icon set and create an static or dynamic menu with icons it seems to go wrong sometimes. First time selecting the icons it reads the icon theme right. But second time (after changing the icon theme) things go wrong. The wrong icon set is then displayed. Not the one in .gtkrc-2.0.

**Comment by erikdubois** [comment]
solved found a difference between latest version and this version
      "$ENV{HOME}/.local/share/applications",

was needed in the config.pl to show the icons

**Comment by macandchief** [comment]
May I ask without opening a new thread here (not topic related): What might be the way to change menu-transparency for the menu by obmenu-generator?

And I tried to find that square font style used on the blogpost screenshot. Do you maybe remember how it is called?
Cheers

**Comment by trizen** [comment]
The font used in the blogpost screenshot is `artwiz snap` (available in the Arch official repos as `extra/artwiz-fonts`).

Regarding the transparency question, Openbox does not provide any compositing effects (such as transparency), and thus requires an external compositor for this purpose.

For compton, see: https://github.com/chjj/compton/issues/55

**Comment by macandchief** [comment]
Great, I was looking for that font style for a while! Thank you for the quick response and the hint regarding the composite manager.
