### ISSUE TITLE
Icons in ~/.icons folder do not show up

### ISSUE THREAD

**Issue by erikdubois** [trizen/obmenu-generator#15]
I have been at it for hours to understand an issue we have with the icons.
Not sure but I do believe this is an actual bug or more an improvement.

In ~/.icons I have dumped 104 icon themes with a total of 169942 icons. Just telling you this because maybe the sheer number may matter in your script.

These icons depend on the core icon themes in /usr/share/icons.
In the index.theme you will find this line (or similar)
`Inherits=Sardi-Orb-Colora,Sardi,Numix-Circle,Numix,Papirus,Moka,Surfn,breeze,gnome,hicolor`

If you select an icon theme from ~/.icons folder then it will look for Sardi-Orb-Colora,Sardi etc...  BUT it will not find those in ~/.icons so it stops and the menu is broken. It should keep looking in /usr/share/icons for the missing themes. My guess the solution is in there to fix the solution with the broken icons.

Solution now 
1. put all icons in ~/.icons
2. put all icons in /usr/share/icons

Tried to work with setting in config.pl as well (also with slash behind it)
icon_dirs_first         => "$ENV{HOME}/.icons",

![archlabs_2017-07-17-53_3840x1080](https://user-images.githubusercontent.com/10594806/28261389-5ec6cb0e-6adf-11e7-81ae-e7462704fd3d.png)
![archlabs_2017-07-17-19_3840x1080](https://user-images.githubusercontent.com/10594806/28261390-5ecaa4e0-6adf-11e7-80fb-4755e606ba73.png)

**Comment by trizen** [comment]
Thank you for taking the time in reporting this issue.

I decided to use the Gtk2 Perl module for resolving the absolute paths to icons, which should be a very robust solution,  compared to the sketchy code in Linux::DesktopFiles.

Please try the latest commit and, if everything is OK,  you may close this issue. Thanks again for the report.

**Comment by erikdubois** [comment]
Hi,
wanted to test it out and went to the AUR
There is no obmenu-generator-git there yet. 
I saw you are maintaining the 0.71 version.
Could you consider making a git version?
Will test it now.

**Comment by erikdubois** [comment]
Obmenu-generator 0.71 is in place.
I replace /usr/bin/obmenu-generator with the one from github

**Comment by trizen** [comment]
Thanks for testing the latest git version.

Make sure that Gtk2 module is installed (gtk2-perl). Additionally, to see what is really going on, please execute `obmenu-generator -i -d` in a terminal and post here the error messages, if any.

I will consider uploading a "-git" version of obmenu-generator to AUR, and also tagging a new version (once we are sure it's working correctly), but this may not happen very soon, unfortunately.

**Comment by erikdubois** [comment]
seems to work with gtk2-perl
make an aur package and I will ask the ArchLabs team to test a bit further
no error messages

**Comment by trizen** [comment]
Finally, a new version is here (https://github.com/trizen/obmenu-generator/releases/tag/0.80), which should fix this issue. If everything is OK, we can close this.

**Comment by erikdubois** [comment]
Hi trizen, 
I am on the point of creating my own spinoff of ArchLabs named https://archmerge.com.
Very happy what you did with the code - svg's are incredibly fast - piped with icons
0-80-1

**Comment by trizen** [comment]
Hi Erik,
I'm very happy to hear that. I wish you all the best on your new project. :+1:

**Comment by JuPlutonic** [comment]
Ok, gtk2 is a new dependency. 
With old dependency Linux::DesktopFiles it always have issue `Can't locate object method "get_icon_path" via package "Linux::DesktopFiles" at /opt/bin/obmenu-generator line 446.`
Now when I installed gtk2-perl with `cpan Gtk2` command the **o-g** working smoothly.
