### ISSUE TITLE
Icons with new  gnome notation

### ISSUE THREAD

**Issue by archmerge** [trizen/obmenu-generator#16]
Hi, 
This is my archmerge account from github aka Erik Dubois from ArchMerge now. 
I encounter a problem I would to run by you. Can you think of a reason why just one icon is not showing up and everything is building fast and nice (my compliments on the latest release).

Peek is the application that is not playing nice.

The only reason I can think off is the new naming : Icon=com.uploadedlobster.peek in the /usr/share/applications  .desktop file.

The peek icon looks good the plank but not in openbox menu.  We get the "there is no image, icon". Same applies to the surfn icon set. Peek icon does not show up either in /usr/share/applications. But we are used to that. As long as it shows up in plank and menu's, that is fine.

Archmerge has Xfce, Openbox and i3. Xfce shows us the icon in the whiskermenu just fine. i3 does not need icons.

Can you think of a reason peek is not playing nice?

Cheers
Erik

Re-edit : filename in /usr/share/applications is also a bit strange - com.uploadlobster.peek.desktop

**Comment by archmerge** [comment]
org.gnome.software has the same issue
thinking it must be the name that is the reason

**Comment by erikdubois** [comment]
I suppose you mean this one
perl-linux-desktopfiles 0.20-1

Getting the new version now
THANKS THANKS THANKS

**Comment by trizen** [comment]
Version 0.21 has just been released yesterday, which includes this particular bug-fix.

See: https://metacpan.org/release/Linux-DesktopFiles
