### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by erikdubois** [trizen/obmenu-generator#17]
Hi Trizen,

i am in the process of making ArchMerge and I was able to hide menu's that concern the openbox environment in the xfce whisker menu.

Is there a possibility to hide the xfce menu's in the openbox menu?

Cheers
Erik

**Comment by trizen** [comment]
Hi Erik,

We can ignore the XFCE specific entries in the Openbox menu by editing the `config.pl` file. In the section `"Linux::DesktopFiles"`, we can add the following condition:

```perl
skip_entry  => [
      {
        key => 'OnlyShowIn',
        re => qr/XFCE/,
      },
],
```

Alternatively, if we want to be more strict about it, we can skip any entry that specifies `XFCE` as a category:

```perl
skip_entry  => [
      {
        key => 'Categories',
        re => qr/XFCE/,
      },
],
```

Here is a working example, using the first condition: [config.pl.zip](https://github.com/trizen/obmenu-generator/files/1326731/config.pl.zip)

If you any other questions, please feel free to ask.

Best regards,
Daniel

**Comment by erikdubois** [comment]
Thanks
I will look into it

Op za 23 sep. 2017 om 20:18 schreef Daniel Șuteu <notifications@github.com>:

**Comment by erikdubois** [comment]
It worked just fine. Great tool. Cheers.
