### ISSUE TITLE
Wine menu

### ISSUE THREAD

**Issue by dmaglio** [trizen/obmenu-generator#19]
I have installed Playonlinux but missing the wine submenu

**Comment by trizen** [comment]
You need to specify the directories that contain the wine desktop files inside the configuration file of `obmenu-generator` (located under: `~/.config/obmenu-generator/config.pl`).

Here is an example that may work:
```perl
 desktop_files_paths     => [
                              "/usr/share/applications",
                              "/usr/local/share/applications",
                              "$ENV{HOME}/.local/share/applications",
                              "$ENV{HOME}/Desktop",
                              glob("$ENV{HOME}/.local/share/applications/wine/Programs/*"),
                            ],
```

Applications that do not specify a category, will appear under the `Other` category.

**Comment by trizen** [comment]
Closing this now...
