### ISSUE TITLE
Does not respect 'OnlyShowIn' and 'NotShowIn' key

### ISSUE THREAD

**Issue by skittleys** [trizen/obmenu-generator#2]
Some packages, for whatever reason, create 2 or more `.desktop` files tailored to particular circumstances, and define these parameters using 'OnlyShownIn' and 'NotShowIn'.[1] obmenu-generator is not parsing this section of the `.desktop` files and discovering these conditions. Therefore, duplicate entries are showing up in the generated menu that would not appear otherwise.

This is not a trivial occurrence that occurs once in a blue moon. Both `synaptic` and `software-properties-gtk` have 2 `.desktop` entries with the following diffs:

```
$ diff synaptic.desktop synaptic-kde.desktop
166c166
< Exec=synaptic-pkexec
> Exec=synaptic
170,172c170,172
< Categories=PackageManager;GTK;System;Settings;
< NotShowIn=KDE;
< X-Ubuntu-Gettext-Domain=synaptic
---
> Categories=PackageManager;System;
> X-KDE-SubstituteUID=true
> OnlyShowIn=KDE;
```

```
$ diff software-properties-gtk.desktop software-properties-gnome.desktop
39,41c39,40
< NotShowIn=GNOME;
< Categories=GNOME;GTK;Settings;X-GNOME-SystemSettings;X-GNOME-Settings-Panel;
< X-GNOME-Settings-Panel=software-properties
---
> OnlyShowIn=GNOME;
> Categories=GNOME;GTK;Settings;X-GNOME-SystemSettings;

```

Let me know if you plan to fix this. I do not do much programming these days, but I am trying to brush up on some scripting languages, so I might take a stab at it myself. 

[1]: http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s05.html

**Comment by trizen** [comment]
Fixed: https://github.com/trizen/obmenu-generator/commit/925a12e8a1436233f88223a449b4724214ac25c5
