### ISSUE TITLE
Not using the correct set of icons

### ISSUE THREAD

**Issue by waterlubber** [trizen/obmenu-generator#20]
...or, far more likely, I'm being an idiot.
I'm currently running Debian 9.3 with Openbox 3.6.1. I'm running `obmenu-generator 0.84`, from the github, as apparently the Debian package is out of date (it doesn't work for me generating icon menus, instead openbox throws an error.) 

Anyway, obmenu-generator DOES properly make a menu, with icons, but the icons it uses are some old and nasty icons that it managed to find, and not the ones that gtk is configured to use (all of my gtk applications manage to use the Arc icon theme). I've tried specifying directories in config.pl, but can't get that to work either. 

Here is my config.pl:
```

our $CONFIG = {
  "editor"              => "gedit",
  "force_icon_size"     => 0,
  "generic_fallback"    => 0,
  "gtk_rc_filename"     => "$ENV{HOME}/.gtkrc-2.0",
  "icon_size"           => 48,
  "Linux::DesktopFiles" => {
                             desktop_files_paths     => ["/usr/share/applications", "/usr/local/share/applications","$ENV{HOME}/.local/share/applications"],
                             gtk_rc_filename         => "$ENV{HOME}/gtkrc-2.0",
                             icon_dirs_first         => "/usr/share/icons/Papirus-Dark",
                             icon_dirs_last          => undef,
                             icon_dirs_second        => "/usr/share/icons/Arc",
                             keep_unknown_categories => 1,
                             skip_entry              => undef,
                             skip_filename_re        => undef,
                             skip_svg_icons          => 0,
                             strict_icon_dirs        => undef,
                             substitutions           => undef,
                             terminalization_format  => "%s -e '%s'",
                             terminalize             => 1,
                             unknown_category_key    => "other",
                           },
  "locale_support"      => 1,
  "missing_icon"        => "gtk-missing-image",
  "terminal"            => "xterm",
  "VERSION"             => 0.84,
}

Any help is appreciated. Thank god there's some activity in this repo.

**Comment by trizen** [comment]
Hi. Since version 0.80, `obmenu-generator` uses the [Gtk2](https://metacpan.org/pod/Gtk2) library to resolve the absolute paths of icons. Due to this change, the `icon_dirs_*` config-options are no longer supported and can be safely removed from the configuration file.

In order for the Gtk2 library to detect and use the current icon theme, it has be specified in the `~/.gtkrc-2.0` file, as:

```perl
gtk-icon-theme-name="Arc"
```

(`lxappearance` can also be used to select the default icon theme)

After this step, you should be able to execute `obmenu-generator -i -s -c -d` in a terminal, which will generate a static menu with icons using the Arc icon theme.

Please let me know if this solves your issue.

**Comment by waterlubber** [comment]
That worked! Thank you for the quick reply. Interestingly enough, the default theme *was* set in `lxappearance`. My previous gtk-rc was as follows:
```
# -- THEME AUTO-WRITTEN BY gtk-theme-switch2 DO NOT EDIT
include "/usr/share/themes/Arc-Darker/gtk-2.0/gtkrc"

include "/home/waterlubber/.gtkrc-2.0.mine"

# -- THEME AUTO-WRITTEN BY gtk-theme-switch2 DO NOT EDIT
```

I expect it was a conflict between lxappearance and gtk-theme-switch2.
