### ISSUE TITLE
Finding .desktop files recursively

### ISSUE THREAD

**Issue by montagdude** [trizen/obmenu-generator#21]
It would be nice if there was a way to make obmenu-generator search recursively for .desktop files in desktop_files_paths. My main reason for wanting this is because Wine places .desktop files in ~/.local/share/applications/wine/Programs/program_name/*.desktop. It would be rather tedious to add each of these directories to desktop_files_paths. Another workaround is to make symlinks for all of these .desktop files in ~/.local/share/applications, but it would be nice if obmenu-generator could find them automatically. Most DEs I've used have no problem finding them automatically with no intervention from me.

**Comment by trizen** [comment]
This can be solved in two different ways: either by using the built-in `glob` Perl function, which expands a shell expression:

```perl
desktop_files_paths => [
  # ...
  glob("$ENV{HOME}/.local/share/applications/wine/Programs/*"),
],
```

or, by recursively finding the directories that contain .desktop files using the `File::Find` module, given a list of initial paths:

```perl
desktop_files_paths => [
  # ...
  do {
    require File::Find;

    my @dirs;
    File::Find::find({no_chdir => 1, wanted => sub {
        if (-f and /\.desktop\z/) {
            push @dirs, $File::Find::dir;
        }
    }},

    # Multiple directories can be provided here, separated by commas
    "$ENV{HOME}/.local/share/applications/wine/Programs",
    "/my/dir2",
    "/my/dir3",
    );

    my %seen;
    grep { !$seen{$_}++ } @dirs;
  },
],
```

Please let me know if this solves the issue. Thanks for reporting!

**Comment by montagdude** [comment]
Thank you for the suggestions. I'm no expert in Perl, but it makes sense to do it that way given that the config file is actually a Perl source file. I tried the first suggestion and it works for me. I haven't tried the second, but I expect it should work too. I will close this now.
