### ISSUE TITLE
gtk_rc_filename ignored?

### ISSUE THREAD

**Issue by napcok** [trizen/obmenu-generator#25]
Looks like obmenu-generator is always looking in $HOME/.gtkrc-2.0 for icon theme name.

I'm trying to have different icons for obmenu and file manager, so I put this line to config.pl:
`  "gtk_rc_filename"     => "$ENV{HOME}/.config/obmenu-generator/.gtkrc-2.0",`

but without success.

**Comment by trizen** [comment]
Starting with version 0.80, obmenu-generator uses the [Gtk2](https://metacpan.org/pod/Gtk2) library to resolve the paths for icons, which uses the current icon theme. The value of `gtk_rc_filename` is used only for detecting if the icon theme was changed by some program (such as `lxappearance`), so obmenu-generator can automatically regenerate the icon cache.

Therefore, the value of `gtk_rc_filename` should always be either `"$ENV{HOME}/.gtkrc-2.0"` (for Gtk2) or `"$ENV{HOME}/.config/gtk-3.0/settings.ini"` (for Gtk3).

In principle, it's possible to read the `gtk_rc_filename` and extract the icon theme name and make the Gtk2 library use that theme for icons, but is it really worth it?!
