### ISSUE TITLE
running -s -i -с gives icons related errors when I use perl and gdk-pixbuf from Homebrew

### ISSUE THREAD

**Issue by JuPlutonic** [trizen/obmenu-generator#27]
OS:Ubuntu 18.10, HomeBrew(linuxbrew 1.9.3), Perl 5.28.1 gdk-pixbuf-2.38.0.

obmenu-generatot 0.85.
Gtk2, Cairo, Pango are needed to be installed when I last time run obmenu-generator. Their installation process demanded me to add to PKG_CONFIG_PATH this file:[gdk-pixbuf-2.0.pc.txt](https://github.com/trizen/obmenu-generator/files/2819020/gdk-pixbuf-2.0.pc.txt).
Now I'm can generate static menu, but without icons. Each menu item generation sends error: 
```
This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/linuxbrew/.linuxbrew/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being. at /usr/local/bin/obmenu-generator line 419.
GdkPixbuf-WARNING **: Cannot open pixbuf loader module file '/home/linuxbrew/.linuxbrew/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': File o directory non esistente
```
**UPD** Command ```mkdir -p /home/linuxbrew/.linuxbrew/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache``` didn't help to icon generation. I don't know how to see more verbose output of the perl program… 
I put old Perl installation to Trash, because something happen to *cpan*, and now I see what it has many Pixbuf -related pods in perl5/lib/perl5/x86_64-linux/Gtk2/Gdk/. And I don't know if I can backup/replace with them pods from my current installation.

**Comment by JuPlutonic** [comment]
-d key  and now -i key giving me error:
(obmenu-generator:4656): GLib-GIO-CRITICAL **: 21:41:44.383: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed
[*] A static menu has been successfully generated!

**Comment by trizen** [comment]
Try to install the `libgtk2-perl` package.

**Comment by JuPlutonic** [comment]
I tried to install it. And tried to recompile Gtk2.pm and tried old GDK Pods from old installation. Nothing helped.

**Comment by trizen** [comment]
Then I cannot really help you. Sorry. It's a local issue.

**Comment by JuPlutonic** [comment]
I will search problems in logs.

**Comment by JuPlutonic** [comment]
Now the problem is gone!
I completely changed order of homebrew, perl sourcing (perl in shell v5.28.1 is from Homebrew), shebang is #!/opt/.linuxbrew/bin/perl in obmenu-regenerator.
