### ISSUE TITLE
Allow generation of schema based on existing menu

### ISSUE THREAD

**Issue by phunni** [trizen/obmenu-generator#28]
Every time I want to generate a new menu, I, currently, have to go through and fix all the little issues that I have with the generated one - which can be a painful process.

I appreciate that I can configure, somewhat, the generated menu through the schema.pl file but I find the syntax a little unfriendly. It would be really useful if I could use my existing - fully tweaked to my liking - menu to generate a schema of which all future menus would be based.

**Comment by trizen** [comment]
This would be a nice idea for a script, but I don't think it's suitable to integrate this functionality into `obmenu-generator`.

To further control what goes into the menu, take a look at `~/.config/obmenu-generator/config.pl`. Especially at the options `skip_filename_re`, `skip_entry` and `substitutions`.

For example, to skip an entry based on the desktop filename, you can use:

```perl
skip_filename_re => qr/^(xterm|xfce4-about)/,       # skips xterm and xfce4-about
```

`skip_entry` is more general and allows skipping an entry based on the value of a given key from the desktop files:

```perl
skip_entry => [
    {key => 'Name',       re => qr/(?:about|terminal)/i},     # skip if name contains "about" or "terminal"
    {key => 'Exec',       re => qr/^xterm/},                  # skip if command starts with "xterm"
    {key => 'OnlyShowIn', re => qr/XFCE/},                    # skip if OnlyShowIn includes XFCE
],
```

Additionally, the `substitutions` option allows replacing values from the desktop files, given a key, a regex and a new value:

```perl
substitutions => [
    {key => 'Exec', re => qr/xterm/, value => 'tilix', global => 1},    # replace xterm with tilix in Exec
],
```

See also: https://metacpan.org/pod/Linux::DesktopFiles
