### ISSUE TITLE
support gtk3?

### ISSUE THREAD

**Issue by xenogenesi** [trizen/obmenu-generator#31]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942365

**Comment by trizen** [comment]
Support for Gtk3 is already available by enabling the `use_gtk3` config-option. (see: https://github.com/trizen/obmenu-generator/commit/d7685c5a95d302b9a998f911e96d7853160bcb5a)

**Comment by xenogenesi** [comment]
Thank you! Sorry I hadn't seen the option, usually I look at the closed issues but this morning I was in a hurry. It works, nice.
