### ISSUE TITLE
Invalid output from pipe-menu "obmenu-generator -i"

### ISSUE THREAD

**Issue by alan12345678** [trizen/obmenu-generator#32]
Don't understand why I keep getting this error?

I'm new to pipe menus, but understand the idea behind the schema.pl etc.

If I start with a completely fresh Openbox, no config.pl in place, I keep getting back to this error.

Is there something missing in my environment (arch linux, openbox, LXQT) that causes this? Have I missed a flag somewhere?

I like the tool, I just don't know where I should be looking for logs or error messages.

**Comment by P90ForRetail** [comment]
Do you have all of the dependencies installed? I had this exact same issue, but then realised that I forgot to install the gtk2-perl package.

**Comment by alan12345678** [comment]
thank you for helping, and indeed I do have that package installed (having read the relevant pages) but I've since abandoned attempts to get it working as it was more rice than absolutely necessary. I'll live perfectly well without it :)
