### ISSUE TITLE
Error at recreating menu with obmenu-generator

### ISSUE THREAD

**Issue by teoten** [trizen/obmenu-generator#33]
I just updated to latest `perl` in arch. Installed a few new packages and now I am getting this error at invoking "Aplications" in menu: "Invalid output from pipe-menu "obmenu-generator".

Then I run as user in terminal: 

`obmenu-generator` 

and get this output:

```
Attempt to reload strict.pm aborted.
Compilation failed in require at /usr/lib/perl5/5.32/core_perl/GDBM_File.pm line 60.
BEGIN failed--compilation aborted at /usr/lib/perl5/5.32/core_perl/GDBM_File.pm line 60.
Compilation failed in require at /usr/bin/obmenu-generator line 450.
```
It seems is related to `perl`. So I tried installing obmenu-generator again. 

it recreated:

```
~/.config/obmenu-generator/config.pl
~/.config/obmenu-generator/schema.pl
```

And solved the problem. Hope this is useful for someone else.

**Comment by trizen** [comment]
This was indeed an issue, due to a change in perl-5.32 regarding undefined values in`%INC`.  (https://github.com/trizen/obmenu-generator/commit/29581c219d220332f5cbd05f9eaec030c75ca08c)

Fixed in obmenu-generator 0.88.
