### ISSUE TITLE
Problem with menu.xml

### ISSUE THREAD

**Issue by dariusity** [trizen/obmenu-generator#35]
I have been trying to look for guides all over and Googling regarding my issue but unfortunately I came to a dead end.
Like every normal instance, after installing from the official Arch repositories, I tried to generate a dynamic menu by typing:
obmenu-generator -i -s
It successfully generated a menu.xml in $HOME/.config/openbox/, so I used the Reconfigure button in the default menu, nothing happened. I tried typing: openbox --reconfigure ; nothing happened. I tried: openbox --restart ; nothing happened.. I logged out and in, nothing happened.. I even rebooted and reinstalled the whole Arch system but still nothing happens. Did I miss any step between after installation and after generating the menu? Is there something I should do to the menu.xml in $HOME/.config/openbox? The only way that will work is to rename /etc/xdg/openbox/menu.xml to something else and then copy the generated menu to /etc/xdg/openbox. Even if I rename the default menu.xml and not copy the generated menu to /etc, still nothing happens too! Hope you dont mind to enlighten me! Cheers.

**Comment by trizen** [comment]
You need to create a local Openbox profile:

```
mkdir -p ~/.config/openbox
cp -a /etc/xdg/openbox/ ~/.config/
```

See also: https://wiki.archlinux.org/index.php/Openbox

**Comment by dariusity** [comment]
I'm sorry,
 [ $HOME/.config/openbox = ~/.config/openbox ]
 for my system, that's how Manjaro, the Arch based distro sets it anyway.

**Comment by trizen** [comment]
How do you start Openbox? Make sure it's executed as user, not as root.

For example, the content of `~/.xinitrc` should be:

```
exec openbox-session
```

then after logging in as user, execute `startx`.

The fact that the menu works only when it's placed in `/etc/xdg/openbox/menu.xml`, implies that Openbox doesn't read your local profile from `~/.config/openbox/`.

**Comment by dariusity** [comment]
It was the login manager that got me in, however there was only 'openbox' session available, if you know why please let me know or I'll try to search for a workaround in Google. Many thanks for the heads up.
