### ISSUE TITLE
[Q] What paths are checked to find an icon?

### ISSUE THREAD

**Issue by txtsd** [trizen/obmenu-generator#37]
I have a .desktop file with an icon entry, and the icon is in /usr/share/icons/hicolor, but obmenu-generator is unable to find the icon, and shows the missing-image icon instead.
How do I debug it?

**Comment by trizen** [comment]
To replace the icon with something else, use the `substitutions` option from `~/.config/obmenu-generator/config.pl`:

```perl
substitutions => [
    {key => 'Icon', re => qr{/usr/share/icons/hicolor/WHATEVER.png}, value => 'NAME OR PATH TO OTHER ICON'},
],
```

**Comment by txtsd** [comment]
Thanks, that's a good way to fix the problem, but I'm trying to understand the internals and why it doesn't work by default when the freedesktop specs are being followed.

**Comment by trizen** [comment]
The icon path used to resolve the icon names, is the same path used by Gtk2 as the default icon theme (specified in `~/.gtkrc-2.0`).

For example, if `~/.gtkrc-2.0` includes:

```ini
gtk-icon-theme-name="Surfn-Papirus-Blue"
```

then the directory `/usr/share/icons/Surfn-Papirus-Blue/` will be used for resolving the icon names to icon files, following its inherited icon themes (specified in `/usr/share/icons/Surfn-Papirus-Blue/index.theme`) when an icon is not found in the main icon theme.

Additionally, try to set `generic_fallback => 1` in the config file. This will try to shorten the icon names at `-` characters before looking at inherited themes.

**Comment by txtsd** [comment]
So it will explicitly look in the current icon theme and the inherited themes. How about `/usr/share/pixmaps`, because that's the only place this particular icon was able to be fetched from? It wouldn't work from any other themes, even ones that inherited hicolor.

**Comment by trizen** [comment]
`obmenu-generator` doesn't look explicitly in those directories. Rather, the Gtk2 (or Gtk3) libraries are used for resolving the icon paths.

Here's the relevant portion of code: https://github.com/trizen/obmenu-generator/blob/master/obmenu-generator#L413..L419

See also: 

- http://gtk2-perl.sourceforge.net/doc/pod/Gtk2/IconTheme.html
- https://lazka.github.io/pgi-docs/Gtk-3.0/classes/IconTheme.html#Gtk.IconTheme.load_icon
- https://gitlab.gnome.org/GNOME/gtk/blob/3.24.23/gtk/gtkicontheme.c#L2088

**Comment by txtsd** [comment]
Thanks!
