### ISSUE TITLE
Successfully generated icon cache, but icons don't appear in menu

### ISSUE THREAD

**Issue by msalini** [trizen/obmenu-generator#38]
- OS: Arch
- perl-gtk3 installed
- use_gtk3=1
- gtk-theme-name="Arc-Clone"  (~/gtkrc-2.0)
- gtk-icon-theme-name="Papirus-Dark" (~/gtkrc-2.0)
- Inherits=Adwaita,"Papirus-Dark",Papirus (~/.icons/default/index.theme)
- Dynamic (-p) menu successfully generated
- Output of ``obmenu-generator -i -d`` 
```
Too late to run INIT block at /usr/lib/perl5/5.32/vendor_perl/Glib/Object/Introspection.pm line 257.
<openbox_pipe_menu>
    <item label="File Manager" icon="/home/username/.config/obmenu-generator/icons/2dd89e059cfc79430318a45a8a89d54b.png"><action name="Execute"><command><![CDATA[xdg-open .]]></command></action></item>
.....
```
The icons do not show up in the menu, despite the fact that the icon cache folder has all the icons properly generated. (see [image](https://ibb.co/BsPVXdG))

Can you help troubleshooting?

Thanks

**Comment by rmlrml** [comment]
Do you have `<showIcons>yes</showIcons>` under the `<menu>` section of your  ~/.config/openbox/rc.xml ?

**Comment by msalini** [comment]
Hi rmlrml,
Apologies for the delayed reply. That was exactly the problem!
It works now. Thanks again for helping me, truly appreciated.
