### ISSUE TITLE
Not all icons found

### ISSUE THREAD

**Issue by zoof** [trizen/obmenu-generator#4]
TeXStudio's application icon is not found.  On my arch based system, the icon path is: /usr/share/icons/hicolor/scalable/apps/texstudio.svg.  Perhaps obmenu-generator does not look for svg files?

**Comment by trizen** [comment]
Maybe the support for svg icons is disabled inside the configuration file.

Try either to regenerate the config by executing `obmenu-generator -r` or manually change the value of `skip_svg_icons` to `0`.

**Comment by zoof** [comment]
Yes, it was disabled in the config file but setting it to 1 does not seem to work. Moreover, running `obmenu-generator -r` seems to reset my `skip_svg_icons` to `1`.

**Comment by trizen** [comment]
What's your version of obmenu-generator? (`obmenu-generator -v`)

**Comment by zoof** [comment]
`obmenu-generator 0.59`

**Comment by trizen** [comment]
That's an old verison. Upgrade to the current version, 0.63, and let me know if the upgrade fixes the issue.

**Comment by zoof** [comment]
Unfortunately it still does not seem to work.

**Comment by trizen** [comment]
I can't confirm the issue. I just installed TeXStudio and the icon is found correctly.

![2015-06-02-190056_1920x1080_scrot](https://cloud.githubusercontent.com/assets/614513/7940503/fad59032-0959-11e5-8743-f85258c806be.png)

Maybe the menu is not up-to-date after the config change? Also, try to run `obmenu-generator -i -d` to regenerate the `icons.db` file.

**Comment by zoof** [comment]
Now it is working.  Not sure if this is what did it but I did a `obmenu-generator -d`.
