### ISSUE TITLE
Invalid output from pipe-menu "usr/bin/obmenu-generator -i"

### ISSUE THREAD

**Issue by leninberg** [trizen/obmenu-generator#41]
Hello

I am running a minimal install of debian 11, and I added openbox, obmenu-generator, tint2... Everything was fine before the upgrade (I upgraded debian 10 to 11 version)

After that, whenever I right-click on screen I never get to see the menu.
A little window with this message shows:

Invalid output from pipe-menu "usr/bin/obmenu-generator -i"

If I run it from the command line I get:

```
Can't locate Linux/DesktopFiles.pm in @INC (you may need to install the Linux::DesktopFiles module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/bin/obmenu-generator line 35.
BEGIN failed--compilation aborted at /usr/bin/obmenu-generator line 35.
```

**UPDATE1:** after running these commands:
```
sudo cpanm Linux::DesktopFiles
sudo cpanm Data::Dump

Note: cpan didn't seem to work, had to use with m at the end (cpanm)
```
I get to see the menu again but only if I remove the option -i (without icons)

When I run from command line:
```
obmenu-generator -i
```

I get this error
```
Can't locate Gtk2.pm in @INC (you may need to install the Gtk2 module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at /usr/bin/obmenu-generator line 390.
```

If I try to install libgtk2-perl (which seems to be [necessary](https://aur.archlinux.org/packages/obmenu-generator/#comment-675165) for a menu with icons)
```
sudo apt-get install libgtk2-perl
```
 it says this package "is not available"
I tried downloading the deb file that corresponds to this package, but then it says there's another dependency that can't be met.

**UPDATE2:** It seems there are some [users](https://www.antixforum.com/forums/topic/libgtk2-perl/page/2/#post-30929) that made it work with icons.

I changed the value (use_gtk3, from 0 to 1) in the file config.pl, but didn't work (no menu is shown and message again Invalid output from pipe-menu "usr/bin/obmenu-generator -i")

When I run from command line:
```
obmenu-generator -i
```

I get this error, at least [another user](https://gitmemory.com/issue/trizen/obmenu-generator/36/735348294) got the same error
```
Can't locate object method "init" via package "Gtk3" at /usr/bin/obmenu-generator line 386.
```
You replied it is a harmless warning, but problem is menu is still not showing at all. Don't know what else I can try.
Any help would be much appreciated, thank you.

*Note: without the -i flag, menu appears and is perfectly fine, but without icons.

**Comment by Head-on-a-Stick** [comment]
Looks like the Perl modules need updating, I'll put out some new bullseye packages later today.

**Comment by trizen** [comment]
You need the [Gtk2](https://metacpan.org/pod/Gtk2) Perl module (or the [Gtk3](https://metacpan.org/pod/Gtk3) module if `use_gtk3` is set to `1`).

Try to install them with the package manager:

```console
sudo apt-get install libgtk2-perl    # for Gtk2
sudo apt-get install libgtk3-perl    # for Gtk3
```

Alternatively, try to install them with `cpanm`:

```console
cpanm --sudo Gtk2
cpanm --sudo Gtk3
```

**Comment by Head-on-a-Stick** [comment]
The Linux::DesktopFiles Perl module is supplied by my perl-linux-desktopfiles package:

https://software.opensuse.org//download.html?project=home%3AHead_on_a_Stick%3Aobmenu-generator&package=perl-linux-desktopfiles

Either grab the .deb package or add my repositories to keep that package and obmenu-generator updated.

**Comment by Head-on-a-Stick** [comment]
>If I try to install libgtk2-perl (which seems to be necessary for a menu with icons)
>```
>sudo apt-get install libgtk2-perl
>```
>it says this package "is not available"
>I tried downloading the deb file that corresponds to this package, but then it says there's another dependency that can't be met.

Please share the exact and full terminal output from those commands, thanks.

Sounds like your repositories are configured incorrectly, this command will show us their disposition:
```
apt policy
```

**Comment by leninberg** [comment]
Terminal output to sudo apt-get install libgtk2-perl
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libgtk2-perl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgtk2-perl' has no installation candidate
```
Terminal output to apt policy
```
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://security.debian.org/debian-security buster/updates/non-free amd64 Packages
     release v=10,o=Debian,a=oldstable,n=buster,l=Debian-Security,c=non-free,b=amd64
     origin security.debian.org
 500 http://security.debian.org/debian-security buster/updates/main amd64 Packages
     release v=10,o=Debian,a=oldstable,n=buster,l=Debian-Security,c=main,b=amd64
     origin security.debian.org
 500 http://security.debian.org/debian-security bullseye-security/main amd64 Packages
     release v=11,o=Debian,a=stable-security,n=bullseye-security,l=Debian-Security,c=main,b=amd64
     origin security.debian.org
 500 http://deb.debian.org/debian bullseye/non-free amd64 Packages
     release v=11.0,o=Debian,a=stable,n=bullseye,l=Debian,c=non-free,b=amd64
     origin deb.debian.org
 500 http://deb.debian.org/debian bullseye/contrib amd64 Packages
     release v=11.0,o=Debian,a=stable,n=bullseye,l=Debian,c=contrib,b=amd64
     origin deb.debian.org
 500 http://deb.debian.org/debian bullseye/main amd64 Packages
     release v=11.0,o=Debian,a=stable,n=bullseye,l=Debian,c=main,b=amd64
     origin deb.debian.org
Pinned packages:
```
Gdebi shows this message
```
Status: Error: Dependency is not satisfiable: perlapi-5.28.1
```
I think [this](https://qa.debian.org/dose/debcheck/unstable_main/latest/packages/libgtk2-perl.html#564734612d5f0e70c8c22e010ebf6e55) is related

**Comment by leninberg** [comment]
I have reinstalled Linux::DesktopFiles from your perl-linux-desktopfiles package (Testing):

[https://software.opensuse.org//download.html?project=home%3AHead_on_a_Stick%3Aobmenu-generator&package=perl-linux-desktopfiles](https://software.opensuse.org//download.html?project=home%3AHead_on_a_Stick%3Aobmenu-generator&package=perl-linux-desktopfiles)

I installed the Gtk3 module with
`sudo apt-get install libgtk3-perl`

Now menu is back with icons.

Thank you.

**Comment by s-kaczmarek** [comment]
I have exactly the same problem. libgtk3-perl is already installed on my system.
