### ISSUE TITLE
"Use" not allowed in experssion at /usr/bin/obmenu-generator lline 32

### ISSUE THREAD

**Issue by AldairbotHerotaku** [trizen/obmenu-generator#47]
"Use" not allowed in experssion at /usr/bin/obmenu-generator lline 32, at end of line
syntax error at /usr/bin/obmenu-generator line 32, near 5.014
BEGIN not safe errors--compilation aborted at /usr/bin/obmenu-generator lline 37

**Comment by trizen** [comment]
Make sure you're using an unmodified version of `obmenu-generaror`. In your version, you seem to have an error regarding the `use` keyword (it should be lowercase).

The SHA256 hash of the current `obmenu-generator` script should be:

```
a5f7093aa6055058033959d9e009cb476e0ab324dc513a9e975d975958aefdd4
```

**Comment by AldairbotHerotaku** [comment]
My letters are lowercase but i writed the logs by hand because i was using xterm. Apparently my 256 hash don't match with that no matters if i rebuild it, i was using 0.90
