### ISSUE TITLE
[Feature Request] `Path=` key support

### ISSUE THREAD

**Issue by akinokonomi** [trizen/obmenu-generator#52]
`Path` key seems to be completely ignored.
Is there any way to make it work via config or something?

Tested with latest version 0.91.

Test desktop entry content:
```desktop
[Desktop Entry]
Type=Application
Name=test
Exec=sh -c "notify-send path \\"\\$(pwd)\\""
Path=/usr/bin
Categories=Utility;
```

Basically, this should happen:
```sh
cd /usr/bin
notify-send path "$(pwd)"
```

Thanks!

EDIT: valid desktop entry command

**Comment by akinokonomi** [comment]
> 7f29fd7

Getting error "Invalid output from pipemenu", if `Path=` contains CJK characters.

Checked with xmllint:

	% obmenu-generator -i | xmllint -
	-:177: parser error : Input is not proper UTF-8, indicate encoding !

---

Also, for some reason, test entry does not work correctly, I get following notification:

```
title: path
message: (pwd)
```

While it should be:

```
title: path
message: /usr/bin
```

Here's the generated item:


```
<item label="test" icon="/path/to/icon.png"><action name="Execute"><command><![CDATA[perl -e "chdir(qq[\/usr\/bin]); exec(qq[sh\ \-c\ \"notify\-send\ path\ \\\\\"\\\\\$\(pwd\)\\\\\"\"])"]]></command></action></item>
```

---

Same entry but without `Path=` key works as expected.

Here's generated item:

```
 <item label="test2" icon="/path/to/icon.png"><action name="Execute"><command><![CDATA[sh -c "notify-send path \"\$(pwd)\""]]></command></action></item>
```

**Comment by trizen** [comment]
Thanks for testing! Can you, please, test the above commit as well to see if it fixes the issues? Thanks!

**Comment by akinokonomi** [comment]
No problem!

Checked latest commit, working great. Did not see any issues, so far.

One thing, though.
I think application should not execute, if `Path=` directory does not exist or can't be accessed.
(Like using shell's `cd dir && cmd`, instead of `cd dir; cmd`.)

Though specification does not say anything about it
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys

> If entry is of type Application, the working directory to run the program in.

For reference, Rofi does not execute application and errors out, if `Path=` dir does not exist.

Of course, because obmenu can't show a graphical error, user would not be able to understand right away why application does not start, but I think it's better that way than having problems when application is executed in a wrong working directory.

Thank you

**Comment by akinokonomi** [comment]
> 20e320f
> Now it also supports commands that include single quotes, like:

I thought single quotes were not supported in `Exec=` key.
Regardless, that commit did not break anything for me, and my previous point was addressed, so I'm gonna close it.

Thank you so much!
