### ISSUE TITLE
Crash with perl 5.38

### ISSUE THREAD

**Issue by Evhorizon** [trizen/obmenu-generator#54]
After updating perl to 5.38 the application fails to run with an error message like "can't locate FILE/*.pm in @INC. Unfortunately I can't remember the name of the file but I think it had something to do with desktopfiles. Downgrading to perl 5.36 indeed works.

**Comment by trizen** [comment]
Perhaps some module is not installed?

Without knowing the exact error message, I can't do anything about it.

**Comment by Evhorizon** [comment]
All the modules were already installed, including perl-linux-desktopfiles. The only thing that changed was the perl release, it looks like it can't find the desktopfiles module in the @INC path? however I will reinstall perl 5.38 again and paste the error output.

**Comment by Evhorizon** [comment]
`Can't locate Linux/DesktopFiles.pm in @INC (you may need to install the Linux::DesktopFiles module) (@INC entries checked: /usr/lib/perl5/site_perl/5.38/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38 /usr/lib/perl5/site_perl/5.38/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.38 /usr/lib/perl5/5.38/x86_64-linux-thread-multi /usr/lib/perl5/5.38) at /usr/bin/obmenu-generator line 35.
BEGIN failed--compilation aborted at /usr/bin/obmenu-generator line 35.
BUT the module is installed..`

**Comment by trizen** [comment]
Perhaps the module is installed only for perl=5.36, but not for 5.38.

Try executing the following command:

```
sudo cpan Linux::DesktopFiles
```

**Comment by Evhorizon** [comment]
yes, it works this way, also executing the command as user without sudo
