### ISSUE TITLE
[Feature Request] `TryExec=` key support

### ISSUE THREAD

**Issue by akinokonomi** [trizen/obmenu-generator#56]
It would be very nice if `TryExec` key were also supported.

From freedesktop specification:

> Path to an executable file on disk used to determine if the program is actually installed.
> If the path is not an absolute path, the file is looked up in the $PATH environment variable.
> If the file is not present or if it is not executable, the entry may be ignored (not be used in menus, for example).
>
> https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys

I wonder if it's somehow possible for me to just use `which` program in `config.pl`'s `skip_entry`?

Thank you!

**Comment by trizen** [comment]
A convoluted way for doing this, using `skip_entry`, would be:

```perl
{ key => "TryExec", re => qr{^(.*)\z(??{`which \Q$1\E`; $? == 0 ? qr{(?!)} : qr{}})} },
```
