### ISSUE TITLE
gtk3 fails after update

### ISSUE THREAD

**Issue by 4zbest** [trizen/obmenu-generator#57]
I updated obmenu-generator last night, now i get this error:

`Can't locate object method "init" via package "Gtk3" at /usr/bin/obmenu-generator line 405.`

Os: Arch
perl-gtk3 is installed and up to date.

**Comment by trizen** [comment]
Strange...

Does the following Perl code work?

```perl
use Gtk3 -init;
my $window = Gtk3::Window->new ('toplevel');
my $button = Gtk3::Button->new ('Quit');
$button->signal_connect (clicked => sub { Gtk3::main_quit });
$window->add ($button);
$window->show_all;
Gtk3::main;
```

**Comment by 4zbest** [comment]
Managed to fix it with:

```
pacman -Rdd perl
pacman -Sc
pacman -S perl
```

Must have gone something wrong with the upgrade of the perl package
