### ISSUE TITLE
A suggestion, Subcategories

### ISSUE THREAD

**Issue by agrufu** [trizen/obmenu-generator#58]
Hi I'm Agustín Rueda Fuentes,

Sorry for my English, the Translation done with Google Translator.

I have been using Linux and Openbox as a Window Manager for several years, and therefore Obmenu-generator to create the menus. I have been studying the source code of Linux:DesktopFiles for some time to create Subcategories within Categories. I don't have much knowledge in Perl programming. Using ChatGPT, I have asked him to rewrite the code to take into account a structure of the Categories and Subcategories of FreeDesktop.org, I share it with you to see if it is possible to include that possibility. The way to distinguish the Categories and Subcategories would be to put the Categories first in the .desktop files, and then the Subcategories. I have not tried it, because I think it needs more code to modify but I don't know how to do it.
[Categorias-Subcategorias.txt](https://github.com/user-attachments/files/16853421/Categorias-Subcategorias.txt)
[DesktopFiles(1).pm.txt](https://github.com/user-attachments/files/16853425/DesktopFiles.1.pm.txt)

**Comment by trizen** [comment]
Hi! I finally managed to work on this feature. :) Thanks for the request!

![1](https://github.com/user-attachments/assets/856cb739-0fa6-4e14-a595-f7e6f17db8d6)
![2](https://github.com/user-attachments/assets/94715e15-19c9-4471-8da7-c205efaa2913)

To use it in the schema file, a category with subcategories can be added as:

```perl
{subcats => ["name", "label", "icon"]},
```

Example:

```perl
    #              NAME            LABEL                ICON
    {subcats => ['utility',     'Accessories', 'applications-utilities']},
    {subcats => ['development', 'Development', 'applications-development']},
    {subcats => ['education',   'Education',   'applications-science']},
    {subcats => ['game',        'Games',       'applications-games']},
    {subcats => ['graphics',    'Graphics',    'applications-graphics']},
    {subcats => ['audiovideo',  'Multimedia',  'applications-multimedia']},
    {subcats => ['network',     'Network',     'applications-internet']},
    {subcats => ['office',      'Office',      'applications-office']},
    {cat     => ['other',       'Other',       'applications-other']},
    {subcats => ['settings',    'Settings',    'applications-accessories']},
    {subcats => ['system',      'System',      'applications-system']},
```

Probably only useful when a user has lots of applications installed.

---

P.S.: requires [Linux::DesktopFiles](https://metacpan.org/pod/Linux::DesktopFiles) >= 0.26.

**Comment by agrufu** [comment]
Hi, thank you so much for your work. I'll continue to tinker with
obmenu-generator... I love it. I'll study the source code in depth, to gain
skills and be able to contribute with more energy.

**Comment by agrufu** [comment]
Hi, after the idea of the script generating menus with subcategories, it
occurred to me to add multilanguage internalization.
For this reason, I have been tinkering with ChatGPT to help me to modify
the files and generate menus based on the system language.
I attach resulting files, can you take a look at them and study whether or
not to add internalization in a new version, please.
I have skimmed the code generated by ChatGPT, I don't have much knowledge
of Perl, but I'm learning.
If my idea bothers you, please receive my sincere apologies and forget it.
I don't want to spoil your good work done with the obmenu-generator script.
