### ISSUE TITLE
very long loading time with icons of paper theme

### ISSUE THREAD

**Issue by asyncial** [trizen/obmenu-generator#7]
Recently, I tried the [paper gtk theme](https://github.com/snwh/paper-gtk-theme) and since then my openbox menu causes very high cpu load and needs up to 5 seconds for showing up. I'm not perfectly sure, if it's a problem of obmenu-generator or openbox, but it ran smoothly at first. Later, after I regenerated the menu this issue came up. If I disable the icons everything is perfectly fine, but even if I change the icons to my stock theme, which worked before, it has the high cpu load.
Greetings, asyncial

**Comment by trizen** [comment]
Hi. What is the full command that you're using inside the menu.xml to generate the menu?

**Comment by asyncial** [comment]
Thank you for the fast answer. Short answer: the static menu with  the `-c` switch worked.
To answer the other questions: In my menu.xml there is no `-d` switch, but there was also no `/usr/bin/perl`. 
The menu was generated with `obmenu-generator -p -i` and `obmenu-generator -s -i`, I tried both, but the `-c` switch seems to be the solution. Thanks for your help :)

**Comment by trizen** [comment]
You're welcome. :)
