### ISSUE TITLE
.deb for debian jessie available

### ISSUE THREAD

**Issue by ohnonot** [trizen/obmenu-generator#9]
there's an unofficial obmenu-generator repository available [here](https://software.opensuse.org/download.html?project=home%3AHead_on_a_Stick%3Aobmenu-generator&package=obmenu-generator) (it _is_ for debian stable, has nothing to do with opensuse). also see [here](https://forums.bunsenlabs.org/viewtopic.php?id=1791).

**Comment by trizen** [comment]
Awesome! Thanks for sharing.

**Comment by waterlubber** [comment]
Do keep in mind that this .deb is out of date and you might be better off just downloading from the repo. I had issues with the .deb
